FROM maven:3.8.5-openjdk-11 as build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME

ADD . $HOME
RUN --mount=type=cache,target=/root/.m2 mvn -f $HOME/pom.xml clean package -DskipTests

FROM openjdk:11.0.7-jre-slim
COPY --from=build /usr/app/medical-api-service/target/*.jar /app/medical-api-service/api-gateway.jar

ENTRYPOINT java -jar /app/medical-api-service/api-gateway.jar