version: '3.4'

services:
  medical-center-config-server:
    build:
      context: ./medical-config-server
      dockerfile: ./Dockerfile
    image: medical-center-config-server
    ports:
    - "8888:8888"
    container_name: medical-center-config-server
  medical-center-service-discovery:
    build:
      context: ./medical-discovery-server
      dockerfile: ./Dockerfile
    image: medical-center-service-discovery
    ports:
    - 8761:8761
    depends_on:
    - medical-center-config-server
    - medical-center-zipkin
    container_name: medical-center-service-discovery
  medical-center-api-gateway:
    build:
      context: ./medical-api-service
      dockerfile: ./Dockerfile
    image: medical-center-api-gateway
    environment:
      - EUREKA_USER=admin
      - EUREKA_PASS=admin
      - EUREKA_SERVER=medical-center-service-discovery
      - EUREKA_PORT=8761
      - SPRING_CLOUD_CONFIG_URI=http://medical-center-config-server:8888
      - KEYCLOAK_SERVER=medical-center-keycloak
      - KEYCLOAK_PORT=8080
    ports:
      - 8050:8050
    depends_on:
      - medical-center-config-server
      - medical-center-service-discovery
      - medical-center-keycloak
      - medical-center-zipkin
    container_name: medical-center-api-gateway
  medical-center-doctors-service:
    build:
      context: ./medical-doctors-service
      dockerfile: ./Dockerfile
    image: medical-center-doctors-service
    environment:
      - EUREKA_USER=admin
      - EUREKA_PASS=admin
      - EUREKA_SERVER=medical-center-service-discovery
      - EUREKA_PORT=8761
      - SPRING_CLOUD_CONFIG_URI=http://medical-center-config-server:8888
      - ZIPKIN_SERVER_URI=http://medical-center-zipkin:9411
      - REDIS_SERVER=medical-center-redis
      - REDIS_PORT=6379
      - REDIS_PASS=root
    depends_on:
      - medical-center-config-server
      - medical-center-service-discovery
      - medical-center-api-gateway
      - medical-center-redis
    container_name: medical-center-doctors-service
  medical-center-patients-service:
    build:
      context: ./medical-patients-service
      dockerfile: ./Dockerfile
    image: medical-center-patients-service
    environment:
      - EUREKA_USER=admin
      - EUREKA_PASS=admin
      - EUREKA_SERVER=medical-center-service-discovery
      - EUREKA_PORT=8761
      - SPRING_CLOUD_CONFIG_URI=http://medical-center-config-server:8888
      - ZIPKIN_SERVER_URI=http://medical-center-zipkin:9411
      - REDIS_SERVER=medical-center-redis
      - REDIS_PORT=6379
      - REDIS_PASS=root
    depends_on:
      - medical-center-config-server
      - medical-center-service-discovery
      - medical-center-api-gateway
      - medical-center-redis
    container_name: medical-center-patients-service
  medical-center-scheduling-service:
    build:
      context: ./medical-scheduling-service
      dockerfile: ./Dockerfile
    image: medical-center-scheduling-service
    environment:
      - EUREKA_USER=admin
      - EUREKA_PASS=admin
      - EUREKA_SERVER=medical-center-service-discovery
      - EUREKA_PORT=8761
      - SPRING_CLOUD_CONFIG_URI=http://medical-center-config-server:8888
      - ZIPKIN_SERVER_URI=http://medical-center-zipkin:9411
      - REDIS_SERVER=medical-center-redis
      - REDIS_PORT=6379
      - REDIS_PASS=root
    depends_on:
      - medical-center-config-server
      - medical-center-service-discovery
      - medical-center-api-gateway
      - medical-center-redis
    container_name: medical-center-scheduling-service
  medical-center-keycloak:
    container_name: medical-center-keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./docker-vendors/scripts/ssl.sh:/init.sh
    ports:
      - 18080:8080
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
  medical-center-zipkin:
    container_name: medical-center-zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  medical-center-redis:
    container_name: medical-center-redis
    image: redis
    command: redis-server --requirepass root
    ports:
      - 6379:6379
