spring:
  redis:
    database: 0
    host: ${REDIS_SERVER:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:root}
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  application:
    name: patients-service
  profiles:
    active: dev
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0

server:
  port: ${PORT:0}
  forward-headers-strategy: framework
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASS:admin}@${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka
logging:
  file:
    name: ./logs/${spring.application.name}.log