version: '3.7'

services:
  course-mc-discovery:
    container_name: dicovery-server
    hostname: dicoveryserver
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - course-medical-center
networks:
  course-medical-center: