server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
logging:
  file:
    name: ./logs/${spring.application.name}.log

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/medical
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: '*'